### ISSUE TITLE
Setup of utPLSQL-coverage-html at local machine.

### ISSUE THREAD

**Issue by shrinathgurav** [utPLSQL/utPLSQL-coverage-html#1]
How do we setup this utility on local machine ? It would be great if you add some details of configuration, which will help those who don't have any knowledge about Ruby language.

**Comment by jgebal** [comment]
Hi @shrinathgurav 
There is no setup needed as well as no Ruby knowledge is needed.
This project is only hosting assets used by `ut_coverage_html_reporter` from [main utPLSQL project](https://github.com/utPLSQL/utPLSQL).
You may find instructions on how to run unit tests with code coverage on the [documentation pages](https://utplsql.github.io/utPLSQL/v3.0.1/userguide/coverage.html).

**Comment by shrinathgurav** [comment]
Thank You @jgebal  will go through that   :)
